openapi: 3.0.3
info:
  title: STD24061
  description: This is a specification of STD24061
  version: 1.0.0
servers:
  - url: "http://localhost:8000"


paths:
  /ping :
    get :
      responses:
        200 :
          description: pong
          content:
            text/plain :
             schema:
               type : string
               example: pong

  /cars:
    get:
      summary: List of cars
      responses:
        '200':
          description: List of cars
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref : '#/components/schemas/Error'
              example:
                - id: 1
                  name: "Alice"
                  email: "alice@example.com"
        '400':
          description: Bad request due to invalid parameter types
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Bad types for provided query parameters"
    components:
      schemas:
        User:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            email:
              type: string
        Error:
          type: object
          properties:
            error:
              type: string

